### PR TITLE
Switch to the MIT License

### PR DESCRIPTION
**Pull request by atosatto**
In order to make the role more open to new contributors and users we decided to drop the GPLv2 license in favor of MIT.

@mongi3, @tiawaz and @winggundamth given that your code is also part of this project, please let us know if you have anything against the re-licensing. If we will not hear any feedback from you in 15 days we will assume you're fine with it and proceed merging this PR.

### CODE REVIEW

**Comment by tiawaz** [comment]
fine by my

**Comment by mongi3** [comment]
Switch away.  Good by me.

**Comment by winggundamth** [comment]
I have no problem with this.

**Comment by atosatto** [comment]
Thank you!

**Pull request merged**
