### PR TITLE
Add support for Rocky and AlmaLinux (which should _for now_ be CentOS like

### PR DESCRIPTION
**Pull request by franklouwers**
Adds support for Alma and Rocky linux, assume those are "identical" to CentOS for now.

### CODE REVIEW

**Comment by Habbie** [comment]
note to self: we want a similar change in the roles for other products

**Comment by Habbie** [comment]
note to self: perhaps we should add rocky and alma to the test matrixes too

**Comment by franklouwers** [comment]
Confirmed to work on Alma 9, should work on Rocky as well.

**Comment by romeroalx** [comment]
Hi @franklouwers,

I have created a new MR (#209 ) for the support of Rocky and AlmaLinux, which includes also testing the installation on those distributions. This MR has additional commits from other MRs. 

Maybe it makes more sense to just close this MR.

**Pull request closed without merging**
